name: Githab-django-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copy directory
      run: cd app/
    - name: Start django  
      run: sudo docker-compose run web django-admin startproject app .
    - name: watch files
      run: ls -l
    - name: Change prava
      run: sudo chown -R $USER:$USER .
    - name: docker up
      run: docker-compose up
    - name: watch active dockers
      run: docker ps
    - name: test web-server
      run: curl http://localhost:8000
    - name: down docker
      run: docker-compose down


#  build_and_pub:
  
#    runs-on: [ubuntu-latest]
#    env:
#      LOGIN: ${{ secrets.DOCKER_LOGIN }}
#      NAME: ${{ secrets.DOCKER_NAME }}
#    steps:
#      - name: Login to docker.io
#        # Сначала мы логинимся в docker.io
#        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#          # Чекаутим код
#      - uses: actions/checkout@master
#      - name: Build image
#          # Собираем image и называем его так как указано в hub.docker т.е. login/repository:version
#        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
#      - name: Push image to docker.io
#          # Пушим образ в registry
#        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
